#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_conf=\
"
frontend  mensah-frontend
        bind *:80
        mode http
        default_backend mensah01-backend
backend mensah01-backend
        balance roundrobin
        server 103694-web-01 35.153.52.50:80 check
        server 63210-web-02 100.25.33.76:80 check
"
echo "$server_conf" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#restart haproxy
sudo service haproxy restart
