#!/usr/bin/env bash
# Bash script to configure Haproxy on  the lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend ang3lp
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 1546-web-01 35.153.52.50:80 check
    server 1546-web-02 54.82.108.93:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
