#!/usr/bin/env bash
# Using if and while statements to print statements

cnt=1

while [[ "$cnt" -le 10 ]]; do
        echo "Best School"
        if [ "$cnt" -eq 9 ]; then
        echo "Hi"
        fi
        cnt=$((cnt+1))
done
